# Generated by Django 4.1.3 on 2022-11-24 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('panther_id', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='judge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('panther_id', models.CharField(max_length=9)),
                ('subject', models.CharField(choices=[('CSC', 'Computer Science'), ('PHY', 'Physics'), ('BIO', 'Biology'), ('CHEM', 'Chemistry')], max_length=4)),
                ('level', models.CharField(choices=[('Grad', 'Graduate Student'), ('Prof', 'Professor')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='session',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('CSC', 'Computer Science'), ('PHY', 'Physics'), ('BIO', 'Biology'), ('CHEM', 'Chemistry')], max_length=4)),
                ('level', models.CharField(choices=[('Undr', 'Undergraduate Student'), ('Grad', 'Graduate Student')], max_length=4)),
            ],
        ),
    ]
