# Generated by Django 4.1.3 on 2022-11-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='session',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
            ],
        ),
    ]
