# Generated by Django 4.1.3 on 2022-11-27 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='administrator',
        ),
    ]
