# Generated by Django 4.1.3 on 2022-11-28 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_delete_administrator'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='judges',
            field=models.ManyToManyField(to='website.judge'),
        ),
        migrations.AddField(
            model_name='session',
            name='submissions',
            field=models.ManyToManyField(to='website.submission'),
        ),
    ]
