# Generated by Django 4.1.3 on 2022-11-30 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_submission_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='winner',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.submission'),
        ),
    ]
