# Generated by Django 4.1.3 on 2022-11-28 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_session_judges_session_submissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='judge',
            name='id',
        ),
        migrations.AlterField(
            model_name='judge',
            name='panther_id',
            field=models.CharField(max_length=9, primary_key=True, serialize=False),
        ),
    ]
