# Generated by Django 4.1.3 on 2022-11-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_session_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judge',
            name='submissions',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='website.submission'),
        ),
    ]
