# Generated by Django 4.1.3 on 2022-11-28 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_judge_id_alter_judge_panther_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judge',
            name='panther_id',
            field=models.CharField(max_length=9, primary_key=True, serialize=False, unique=True),
        ),
    ]
