# Generated by Django 4.1.3 on 2022-11-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_judge_submissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('judge', models.ManyToManyField(to='website.judge')),
                ('submission', models.ManyToManyField(to='website.submission')),
            ],
        ),
    ]
