# Generated by Django 4.1.3 on 2022-11-30 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='score',
            new_name='given_score',
        ),
    ]
