# Generated by Django 4.1.3 on 2022-11-30 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_rename_score_score_given_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='judge',
        ),
        migrations.RemoveField(
            model_name='score',
            name='submission',
        ),
        migrations.AddField(
            model_name='score',
            name='judge',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='website.judge'),
        ),
        migrations.AddField(
            model_name='score',
            name='submission',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='website.submission'),
        ),
    ]
