# Generated by Django 4.1.3 on 2022-11-30 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_remove_score_judge_remove_score_submission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='score',
            field=models.IntegerField(default=None),
        ),
        migrations.DeleteModel(
            name='score',
        ),
    ]
