# Generated by Django 4.1.3 on 2022-11-30 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_alter_submission_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='score',
        ),
    ]
