# Generated by Django 4.1.3 on 2022-11-30 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_remove_submission_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
